### ISSUE TITLE
The AdGuard kb doesn’t follow the system theme

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/KnowledgeBase#126] opened 2023-02-07 11:49 UTC
The AdGuard kb doesn’t follow the system theme in Safari for macOS. Please consider implementing this.

macOS: 13.2 (22D49)
Safari: 16.3 (18614.4.6.1.5)

Reported by @jslawler

**Comment by Bhavyawahie** [comment] 2023-02-22 21:09
@Eugene-Savenko The system theme in general doesn't follow as the default theme on the page load, regardless of the OS and browser.

I am working on a fix for this very problem.

**Comment by Bhavyawahie** [comment] 2023-02-22 21:38
#141

**Comment by Bhavyawahie** [comment] 2023-02-22 21:40
> @Eugene-Savenko The system theme in general doesn't follow as the default theme on the page load, regardless of the OS and browser.
> 
> I am working on a fix for this very problem.

#141 is the solution that I have devised, kindly look if it works!

**Closed** 2023-03-07 20:21 UTC
Labels: enhancement

**Comment by jslawler** [comment] 2023-03-07 20:46
As the issue is closed now, I presume this is now in production.

If it is, I'm still not seeing them on Safari Version 16.4 (18615.1.24.110.1) for macOS, or iOS 16.4 b2 Safari.

System theme is dark, yet the website shows light when loaded until manually changed to dark.

**Comment by sc0rp10** [comment] 2023-03-07 21:07
@jslawler when a PR is merged on GitHub, it will undergo an internal testing-staging-deployment cycle. After this the results will appear on the production website. I assume that it will take 2-3 business days.
